### ISSUE TITLE
Another call to "densityplot"

### ISSUE THREAD

**Issue by znmeb** [beanumber/openWARData#7]
I've forked openWARData and am trying to build it with RStudio. Currently it's failing the R CMD CHECK with

```
> # Get data from yesterday
> ds = getrWAR()
> mosaic::densityplot(~WAR, data=ds, plot.points=FALSE)
Error: 'densityplot' is not an exported object from 'namespace:mosaic'
Execution halted
```

I guess the easiest fix would be to delete that example but I didn't want to do a pull request without checking.

**Comment by znmeb** [comment]
I should note that I'm using Mosaic from Github, not from CRAN - specifically, https://github.com/ProjectMOSAIC/mosaic/releases/tag/v0.10.0

**Comment by beanumber** [comment]
This has been removed.
